### ISSUE TITLE
Array type in resource model rendering incorrectly as object

### ISSUE THREAD

**Issue by sem247** [DapperDox/dapperdox#34] opened 2017-01-11 15:19 UTC
The following is a fragment from a response definition in my swagger doc:

```
"definitions": {
        "Dataset": {
            "title": “Dataset model”,
            "type": "object",
            "properties": {
                "items_per_page": {
                    "type": "integer",
                    "description": "Number of items returned in a page of response"
                },
                "start_index": {
                    "type": "integer",
                    "description": "Index of the starting item"
                },
                "total_items": {
                    "type": "integer",
                    "description": "The total number of items in dataset"
                },
                "items": {
                    "description": “Dataset items",
                    "minItems": 0,
                    "uniqueItems": true,
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Metadata"
                    }
                }
            }
        },
        "Metadata": {
            "title": “Metadata model",
            "type": "object",
        .
        .
        .
```
DapperDox renders the “Dataset.items” resource  incorrectly as an object rather than an array:

```
{
    "items": {
        "id": "string",
        "kind": "string",
        "links": [
            {
                "url": "string"
            }
        ],
        "title": "string"
    },
    "items_per_page": "integer",
    "start_index": "integer",
    "total_items": "integer"
}
```
Swagger UI correctly renders it as:

```
{
  "items_per_page": 0,
  "start_index": 0,
  "total_items": 0,
  "items": [
    {
      "id": "string",
      "kind": "string",
      "title": "string",
      "links": [
        {
          "url": "string"
        }
      ]
    }
  ]
}
```
The items field is an array, not an object.

**Comment by zxchris** [comment] 2017-01-11 18:23
Can you give the spec of your Metadata definition? I can't replicate exactly what you're seeing but can cause a different error.

My first test worked perfectly when I duplicated your Dataset definition, but referenced one of my own object models instead of your Metadata, giving this:

```
{
    "dataset": {
        "items": [
            {
                "debtors": {
                    "value": "integer"
                },
                "employee": {
                    "value": "integer"
                }
            }
        ],
        "items_per_page": "integer",
        "start_index": "integer",
        "total_items": "integer"
    }
}
```
Which is correct,  **but** if I reference another model I have in place of Metadata, then DapperDox errors, which is surprising, but good because I can see exactly where that occurs and I expect it is related to your issue in some way.

As an aside, processing Swagger arrays is a little tricky, as you have to juggle both knowledge that it is an array, and an array of _what_. There are also several ways of expressing the same thing, which complicated things further.

I suspect DapperDox is getting confused by something in your Metadata definition that is a test case we've not come across before. The fact I can get DapperDox to fail too, is also interesting and i will look at that in the meantime.

If you can give us a complete swagger example that demonstrates the problem, that will help massively, and extend our test cases ;-)

**Comment by zxchris** [comment] 2017-01-13 13:22
I've resolved the error I was getting. This was caused by my `items` array member referencing an object definition that had members that were *all* readOnly. When DapperDox creates a resource for a POST/PUT, it filters out the readOnly members and ended up with a null object in this case, causing the error.

If made DapperDox expect this condition so that it doesn't error, and produces the result below:

```
{
    "dataset": {
        "items": null,
        "items_per_page": "integer",
        "start_index": "integer",
        "total_items": "integer"
    },
    "made_up_to": "date"
}
```

Note the `null` for the `items` member. A more *correct* Swagger specification would have defined `items` as `readOnly`, excluding it completely from the JSON, and so I'm not proposing to implement anything more fancy.

**Comment by sem247** [comment] 2017-01-18 16:28
Thanks for looking into this.  I'll double check if it's ok to share my spec on this forum.  Having said that, I do see a difference between my model and your test model.  The object in my `items` array has got another array `links`.

```
{
  "items_per_page": 0,
  "start_index": 0,
  "total_items": 0,
  "items": [
    {
      "id": "string",
      "kind": "string",
      "title": "string",
      "links": [
        {
          "url": "string"
        }
      ]
    }
  ]
}
```

For your test spec, the object in the `items` array doesn't have any array.
```
{
    "dataset": {
        "items": [
            {
                "debtors": {
                    "value": "integer"
                },
                "employee": {
                    "value": "integer"
                }
            }
        ],
        "items_per_page": "integer",
        "start_index": "integer",
        "total_items": "integer"
    }
}
```

**Comment by zxchris** [comment] 2017-01-27 17:19
Thanks. If you can't share your spec, if you can put something together which you *can* share that reproduces the issue, then we've a shared test case!

In the meantime I'll have a look at adding another sub-array element and see what happens.

**Comment by ralphvanetten** [comment] 2017-01-31 10:32
I have the same issue where an array is rendered as an object.

The stripped down version of my spec which reproduces this issue is:

```
{
    "x-navigateMethodsByName": true,
    "definitions": {
    "AccountList": {
      "type": "object",
      "title": "AccountList",
      "properties": {
        "account": {
          "type": "array",
          "title": "List with accounts",
          "items": {
            "$ref": "#/definitions/AccountInfo"
          }
        }
      }
    },
    "AccountInfo": {
      "type": "object",
      "title": "Account information",
      "properties": {
        "displayName": {
          "type": "string",
          "title": "Display name"
        }
      }
    }
  },
  "info": {
    "description": "Minimal example for issue #34",
    "title": "issue #34"
  },
  "swagger": "2.0",
  "paths": {
    "/account": {
      "get": {
        "summary": "List accounts",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "Success",
            "schema": {
              "$ref": "#/definitions/AccountList"
            }
          }
        }
      }
    }
  }
}
```

This is rendered by dapperdox as:

```
{
    "account": {
        "displayName": "string"
    }
}
```

In swagger-ui it is rendered correctly as:

```
{
    "account": [
        {
            "displayName": "string"
        }
    ]
}
```

**Comment by zxchris** [comment] 2017-01-31 21:47
Great, thanks. I can reproduce.
I'll take a look.

**Comment by zxchris** [comment] 2017-02-01 16:10
I've found _why_ it is getting confused, but not _where_
```
"AccountInfo": {
      "type": "object",
      "title": "Account information",
```
Setting the type to "object" is overriding the parent set type of "array"... remove the object type declaration in `AccountInfo`, and it works as expected.

I'm tracking down whether this is DapperDox getting confused, or the OpenAPI parser DapperDox is using (go-openapi).

Update soon!

**Comment by zxchris** [comment] 2017-02-01 16:58
I found another problem, not sure it's technically a "valid" thing to do in a specification (but I've not checked, so could be wrong!!) but you've specified a `"title"` member for `"displayName"` where I would have thought you'd have a `"description"` member.

Anyway, the `"title"` messes up the namespacing of the elements, for some reason. Looking into that too...

**Comment by ralphvanetten** [comment] 2017-02-02 08:29
> Anyway, the "title" messes up the namespacing of the elements

I noticed the same and I've created https://github.com/DapperDox/dapperdox/issues/36 earlier, I think it's about the same issue.

Thanks!

**Comment by zxchris** [comment] 2017-02-03 22:28
I think I have a fix for this, which I will push shortly once I've done a bit more testing.

**Comment by ralphvanetten** [comment] 2017-02-04 09:36
Thanks!

**Comment by zxchris** [comment] 2017-02-08 17:17
Fixed in issue/34 merged into master

**Closed by zxchris** 2017-02-08 17:17 UTC
Labels: bug
